config/routes.rb
Clientlounge::Application.routes.draw do
  namespace :admin do resources :projects end

  get "dashboard/index"

  namespace :admin do resources :pages end

  get "welcome/index"

  get "welcome/contact"

  root :to => "welcome#index"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id(.:format)))'
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/page.rb
class Admin::Page < ActiveRecord::Base
  validates_presence_of :title
  has_friendly_id :title, :use_slug => true, :cache_column => 'cached_slug'
end

app/models/admin/project.rb
class Admin::Project < ActiveRecord::Base
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  def index
  end

end

app/controllers/admin/pages_controller.rb
class Admin::PagesController < ApplicationController
  layout 'admin'
  # GET /admin/pages
  # GET /admin/pages.xml
  def index
    @admin_pages = Admin::Page.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @admin_pages }
    end
  end

  # GET /admin/pages/1
  # GET /admin/pages/1.xml
  def show
    @admin_page = Admin::Page.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @admin_page }
    end
  end

  # GET /admin/pages/new
  # GET /admin/pages/new.xml
  def new
    @admin_page = Admin::Page.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @admin_page }
    end
  end

  # GET /admin/pages/1/edit
  def edit
    @admin_page = Admin::Page.find(params[:id])
  end

  # POST /admin/pages
  # POST /admin/pages.xml
  def create
    @admin_page = Admin::Page.new(params[:admin_page])

    respond_to do |format|
      if @admin_page.save
        format.html { redirect_to(@admin_page, :notice => 'Page was successfully created.') }
        format.xml  { render :xml => @admin_page, :status => :created, :location => @admin_page }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @admin_page.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /admin/pages/1
  # PUT /admin/pages/1.xml
  def update
    @admin_page = Admin::Page.find(params[:id])

    respond_to do |format|
      if @admin_page.update_attributes(params[:admin_page])
        format.html { redirect_to(@admin_page, :notice => 'Page was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @admin_page.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/pages/1
  # DELETE /admin/pages/1.xml
  def destroy
    @admin_page = Admin::Page.find(params[:id])
    @admin_page.destroy

    respond_to do |format|
      format.html { redirect_to(admin_pages_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController
  layout 'admin'
  # GET /admin/projects
  # GET /admin/projects.xml
  def index
    @admin_projects = Admin::Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @admin_projects }
    end
  end

  # GET /admin/projects/1
  # GET /admin/projects/1.xml
  def show
    @admin_project = Admin::Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @admin_project }
    end
  end

  # GET /admin/projects/new
  # GET /admin/projects/new.xml
  def new
    @admin_project = Admin::Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @admin_project }
    end
  end

  # GET /admin/projects/1/edit
  def edit
    @admin_project = Admin::Project.find(params[:id])
  end

  # POST /admin/projects
  # POST /admin/projects.xml
  def create
    @admin_project = Admin::Project.new(params[:admin_project])

    respond_to do |format|
      if @admin_project.save
        format.html { redirect_to(@admin_project, :notice => 'Project was successfully created.') }
        format.xml  { render :xml => @admin_project, :status => :created, :location => @admin_project }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @admin_project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /admin/projects/1
  # PUT /admin/projects/1.xml
  def update
    @admin_project = Admin::Project.find(params[:id])

    respond_to do |format|
      if @admin_project.update_attributes(params[:admin_project])
        format.html { redirect_to(@admin_project, :notice => 'Project was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @admin_project.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/projects/1
  # DELETE /admin/projects/1.xml
  def destroy
    @admin_project = Admin::Project.find(params[:id])
    @admin_project.destroy

    respond_to do |format|
      format.html { redirect_to(admin_projects_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def contact
    render :layout => 'sign'
  end

end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/pages_helper.rb
module Admin::PagesHelper
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/dashboard/index.html.erb
<h1>Admin::Dashboard#index</h1>
<p>Find me in app/views/admin/dashboard/index.html.erb</p>

app/views/admin/pages/_form.html.erb
<%= form_for(@admin_page) do |f| %>
  <% if @admin_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_page.errors.count, "error") %> prohibited this admin_page from being saved:</h2>

      <ul>
      <% @admin_page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="group">
    <%= f.label :title, :class =>'label' %>
    <%= f.text_field :title, :class=>"text_field"  %>
  </div>
  <div class="group">
    <%= f.label :link_text, :class =>'label' %>
    <%= f.text_field :link_text, :class=>"text_field" %>
  </div>
  <div class="group">
    <%= f.label :meta_keywords, :class=>'label' %>
    <%= f.text_field :meta_keywords, :class=>"text_field" %>
  </div>
  <div class="group">
    <%= f.label :meta_description, :class=>'label' %>
    <%= f.text_field :meta_description, :class=>"text_field" %>
  </div>
  <div class="group">
    <%= f.label :content, :class=>'label' %>
    <%= f.text_area :content, :class=>"text_area" %>
  </div>
  <div class="group">
    <%= f.check_box :active,:class =>'checkbox'  %>
    <%= f.label :active,:class =>'checkbox' %>
  </div>
  <div class="group">
    <%= f.check_box :members_only,:class =>'checkbox'  %>
    <%= f.label :members_only,:class =>'checkbox'  %>
  </div>
  <div class="group">
    <%= f.check_box :navigation,:class =>'checkbox'  %>
    <%= f.label :navigation,:class =>'checkbox'  %>    
  </div>
  <div class="group navform wat-cf">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/pages/edit.html.erb
<h1>Editing admin_page</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_page %> |
<%= link_to 'Back', admin_pages_path %>

app/views/admin/pages/index.html.erb
<h1>Listing admin_pages</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Link text</th>
    <th>Cached slug</th>
    <th>Meta keywords</th>
    <th>Meta description</th>
    <th>Content</th>
    <th>Active</th>
    <th>Members only</th>
    <th>Navigation</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @admin_pages.each do |admin_page| %>
  <tr>
    <td><%= admin_page.title %></td>
    <td><%= admin_page.link_text %></td>
    <td><%= admin_page.cached_slug %></td>
    <td><%= admin_page.meta_keywords %></td>
    <td><%= admin_page.meta_description %></td>
    <td><%= admin_page.content %></td>
    <td><%= admin_page.active %></td>
    <td><%= admin_page.members_only %></td>
    <td><%= admin_page.navigation %></td>
    <td><%= link_to 'Show', admin_page %></td>
    <td><%= link_to 'Edit', edit_admin_page_path(admin_page) %></td>
    <td><%= link_to 'Destroy', admin_page, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Page', new_admin_page_path %>

app/views/admin/pages/new.html.erb
<div class="block" id="block-forms"> 
	<div class="content"> 
    <h2 class="title">New Page</h2> 
    <div class="inner">
      <%= render 'form' %>
    </div>
  </div>
<%= link_to 'Back', admin_pages_path %>
</div>

app/views/admin/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @admin_page.title %>
</p>

<p>
  <b>Link text:</b>
  <%= @admin_page.link_text %>
</p>

<p>
  <b>Cached slug:</b>
  <%= @admin_page.cached_slug %>
</p>

<p>
  <b>Meta keywords:</b>
  <%= @admin_page.meta_keywords %>
</p>

<p>
  <b>Meta description:</b>
  <%= @admin_page.meta_description %>
</p>

<p>
  <b>Content:</b>
  <%= @admin_page.content %>
</p>

<p>
  <b>Active:</b>
  <%= @admin_page.active %>
</p>

<p>
  <b>Members only:</b>
  <%= @admin_page.members_only %>
</p>

<p>
  <b>Navigation:</b>
  <%= @admin_page.navigation %>
</p>


<%= link_to 'Edit', edit_admin_page_path(@admin_page) %> |
<%= link_to 'Back', admin_pages_path %>

app/views/admin/projects/_form.html.erb
<%= form_for(@admin_project) do |f| %>
  <% if @admin_project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_project.errors.count, "error") %> prohibited this admin_project from being saved:</h2>

      <ul>
      <% @admin_project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/projects/edit.html.erb
<h1>Editing admin_project</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_project %> |
<%= link_to 'Back', admin_projects_path %>

app/views/admin/projects/index.html.erb
<h1>Listing admin_projects</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @admin_projects.each do |admin_project| %>
  <tr>
    <td><%= admin_project.title %></td>
    <td><%= admin_project.description %></td>
    <td><%= link_to 'Show', admin_project %></td>
    <td><%= link_to 'Edit', edit_admin_project_path(admin_project) %></td>
    <td><%= link_to 'Destroy', admin_project, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Project', new_admin_project_path %>

app/views/admin/projects/new.html.erb
<h1>New admin_project</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_projects_path %>

app/views/admin/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @admin_project.title %>
</p>

<p>
  <b>Description:</b>
  <%= @admin_project.description %>
</p>


<%= link_to 'Edit', edit_admin_project_path(@admin_project) %> |
<%= link_to 'Back', admin_projects_path %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Web App</title>
  <%= stylesheet_link_tag "web-app-theme/base", "web-app-theme/themes/warehouse/style", "web-app-theme/override", :cache => true %>
  <%= javascript_include_tag :defaults, :cache => true %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="container">
    <div id="header">
      <h1><a href="/">Web App</a></h1>
      <div id="user-navigation">
        <ul class="wat-cf">
          <li><a href="#"><%= t("web-app-theme.profile", :default => "Profile") %></a></li>
          <li><a href="#"><%= t("web-app-theme.settings", :default => "Settings") %></a></li>
          <li><a href="/logout" class="logout"><%= t("web-app-theme.logout", :default => "Logout") %></a></li>
        </ul>
      </div>
      <div id="main-navigation">
        <ul class="wat-cf"></ul>
      </div>
    </div>    
    <div id="wrapper" class="wat-cf">
      <div class="flash">
        <% flash.each do |type, message| -%>
          <div class="message <%= type %>">
            <p><%= message %></p>
          </div>
        <% end -%>
      </div>
      <div id="main">
        <%= yield %>
        <div id="footer">
          <div class="block">
            <p>Copyright &copy; <%= Time.now.year %> Web App.</p>
          </div>      
        </div>
      </div>
      <div id="sidebar">
        <%= yield :sidebar %>
      </div>
    </div>    
  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> Client Lounge</title>
  <%= stylesheet_link_tag "reset","960","text","application"%>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <%= yield(:head) %>
</head>
<body>
<div class="container_12" id="header">
	<div class="grid_8">
		<%= image_tag('client-lounge-logo.jpg')%>
	</div>
	<div class="grid_4">
		<p>The online project management tool for mycompanynamehere</p>
	</div>
</div>
<div class="container_12" id="navigation">
	<div class="grid_12">
		<ul>
			<li><%= link_to "Home", root_url %></li>
			<li><a href="">link somewhere</a></li>
			<li><a href="">link somewhere</a></li>
			<li><a href="">link somewhere</a></li>
			<li><a href="">link somewhere</a></li>
			<li><a href="">link somewhere</a></li>
			<li><a href="">Contact Us</a></li>
		</ul>
	</div>
</div>
<div class="container_12" id="main">
	<% flash.each do |name, msg| %>
    <%= content_tag :div, msg, :id => "flash_#{name}", :class => 'grid_12' %>
  <% end %>
	<div class="grid_12">
  	<%= content_tag :h1, yield(:title)%>
  </div>
	<div class="grid_8">
		<%= yield %>
	</div>
	<div class="grid_4">
		<%= yield(:sidebar)%>
	</div>
</div>
<div class="container_12" id="footer">
	
</div>


</body>
</html>

app/views/layouts/sign.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title)%></title>
  <%= stylesheet_link_tag "web-app-theme/base", "web-app-theme/themes/default/style", "web-app-theme/override"%>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="container">
    <div id="box">
      <%= yield %>            
    </div>
  </div>
</body>
</html>

app/views/welcome/contact.html.erb
<% content_for :title do -%>
	Contact Us
<% end -%>
<div class="block" id="block-login">
	<h2>Contact Us</h2>
	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>

app/views/welcome/index.html.erb
<% content_for :title do -%>Client Lounge<% end -%>
<p>This is just some dummy text for the client lounge home page, at the moment the project is not complete if you are looking at this. Soon there will be heaps of features.</p>
<p>If you're wondering why I am doing this, it is because I want an easy way to manage my clients online and give them access where they can download their projects. I am a freelancer undertaking web and simple graphic design and often find myself having to email and re-email items and upload them without structure.</p>
<p>I am aware that there are already a number of solutions out there but I really wanted one that I could customise myself, so I started from scratch to suit my workflow. I am open to any feature suggestions and recommendations that anyone with previous experience can offer.</p>